[package]
name = "yprox"
description = "A modifying, multiplexer tcp proxy server tool and library."
version = "0.2.1"
authors = ["Felipe Coury <felipe.coury@gmail.com>", "mo8bit"]
edition = "2021"
license = "MIT"
repository = "https://github.com/fcoury/yprox"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
mlua = { version = "0.9.1", features = ["lua54", "send"] }
