[package]
name = "yprox"
description = "A modifying, multiplexer tcp proxy server tool and library."
version = "0.1.1"
authors = ["Felipe Coury <felipe.coury@gmail.com>"]
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.23", features = ["derive"] }
futures = "0.3.28"
mlua = { version = "0.9.1", features = ["lua54"] }
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7.8", features = ["full"] }
